name: rcds check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        path: 'challs'
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: Download rcds
      uses: actions/checkout@v4
      with:
        repository: 'uclaacm/rcds'
        path: 'rcds'
    - name: Install rcds
      working-directory: 'rcds'
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Overwrite rcds.yaml with basic blank config
      working-directory: 'challs'
      run: |
        (echo "docker:"
        echo "  image:"
        echo "    prefix: localhost:5000/cyber-fall-gm-f23") > rcds.yaml
    - name: Run a temporary local docker registry
      run: |
        docker run -d -p 5000:5000 --restart=always registry:2
    - name: Run rcds
      working-directory: 'challs'
      run: |
        rcds deploy
